services:
  - type: web
    name: anthro-calculator
    env: python
    plan: free
    buildCommand: buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn anthro_app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: anthro_app.settings
      - key: PYTHON_VERSION
        value: "3.10"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
